module LocatorCartPage
    PIC_SECTION ||= "div[class='css-1sl137g-control']"
    PIC_SELECT  ||= "//div[@class='css-1su63w0-menu']//p[contains(text(), 'Darwin')]"
    TOGGLE_NON_MEMBER ||= "//label[@class='chakra-switch css-3h6sr1']"
    NAMA_NON_MEMBER_FIELD ||= "//input[@data-test-id='pos-checkout-customer-name']"
    NOHP_NON_MEMBER_FIELD ||= "//input[@data-test-id='pos-checkout-customer-number']"
    EMAIL_NON_MEMBER_FIELD ||= "//input[@data-test-id='pos-checkout-customer-email']"
    BTN_CONFIRM_NON_MEMBER ||= "//button[@data-test-id='pos-checkout-non-member-btn']"
    SEARCH_SKU ||= "(//div[@class='css-1579zyh']//input)[2]"
    TYPING_SKU ||= "div[class='css-1txham7-control']"
    BTN_LANJUTKAN ||= "//button[normalize-space(text())='Lanjutkan']"
    BADGES_USER ||= "//div[@data-test-id='customer-detail-badge-0']"
    ERROR_NAMA_NON_MEMBER ||= "//div[normalize-space(text())='Nama Customer harus diisi']"
    ERROR_HOHP_NON_MEMBER ||= "//div[normalize-space(text())='Nomor Telepon harus diisi']"
    ERROR_EMAIL_NON_MEMBER ||= "//div[normalize-space(text())='Format email tidak sesuai']"
    SEARCH_MEMBER ||= "(//div[@class='react-select__input-container css-1579zyh']//input)"
end